version: '2'

services:
  ctfd:  
    build: .
    user: root
    restart: always
    environment:
      - SECRET_KEY=1020304050
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:master_root_password@maxscale:4006/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=2
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=- 
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - maxscale
      - cache
    networks:
        default:
        internal:

  master1:
    image: 'bitnami/mariadb:latest'
    container_name: master1
    restart: always
    ports:
      - '3306'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
    volumes:
      - .data/mysql:/bitnami/mariadb 
    networks:
        internal:

  slave1:
    image: 'bitnami/mariadb:latest'
    container_name: slave1
    restart: always
    ports:
      - '3306'
    depends_on:
      - master1
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=master1
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password
    networks:
        internal:

  slave2:
    image: 'bitnami/mariadb:latest'
    container_name: slave2
    restart: always
    depends_on:
      - master1
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=master1
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password
    networks:
        internal:

  maxscale:
    build: maxscale/
    container_name: maxscale
    restart: always
    depends_on:
      - master1
      - slave1
      - slave2
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf
    networks:
        internal:
  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/hata.html:/usr/share/nginx/html/hata.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ctfd
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: maxscale
      PMA_PORT: 4006
      PMA_ARBITRARY: 1
    restart: always
    networks:
      default:
      internal:
    ports:
      - 81:80
 

 
networks:
    default:
    internal:
        internal: true
